### PR TITLE
Change plugin name + Add Constants

### PR DESCRIPTION
**Pull request by zulfgani**
This PR renames the plugin as discussed [here](https://github.com/Classic-Commerce/cc-compat-woo/issues/1).

Defines the plugin's constants and applies a filter function to remove the View Details link on the plugins page.

### CODE REVIEW

**Comment by timbocode** [comment]
Looks good for merge

**Comment by bahiirwa** [comment]
Looks good to merge.

Side note: Should we adopt a process of having one PR do one change for easier review?

**Comment by zulfgani** [comment]
> Side note: Should we adopt a process of having one PR do one change for easier review?

Yes we should do that going forward.

**Comment by timbocode** [comment]
> Side note: Should we adopt a process of having one PR do one change for easier review?

Yes, I agree.

**Pull request merged**
