### PR TITLE
Clean Install of Compat plugin

### LINKED ISSUE #3: Change folder name on plugin download and activate it.
As agreed in https://github.com/ClassicPress-research/classic-commerce/issues/131#issuecomment-565746774

1. We have delegated the uninstallation of the WooCommerce plugin to the website owner.
1. This plugin on install and activation runs under the folder named **cc-compat-woo** with file **woocommerce.php**
1. We need to rewrite its name to folder named **woocommerce** with file **woocommerce.php**
1. Issue arises - CP will reocgnize the that plugin **cc-compat-woo/woocommerce.php** is no longer active in the plugins_options array. With this, the newly renamed  **woocommerce*/woocommerce.php** won't work. It is inactive until activated again.
1. The Challenge is rename the folder and activate it. 

Of course this is easy for an experiences developer to use a command line and accomplish all these tasks. How do we get the ordinary user who downloaded this plugin to do these tasks in one click of the button?

### PR DESCRIPTION
**Pull request by bahiirwa**
This is a rough Idea I had for closing #3. We could build on this. 

The only restrictions I see are if a user has file write permissions locked. In which case, that user can not auto install plugins unless they provide FTP logins to CP.

Closes #3.

### CODE REVIEW

**Review by timbocode — CHANGES_REQUESTED** [review]
As per Slack discussion, use WP_Filesystem instead of PHP functions.

**Comment by bahiirwa** [comment]
As per slack, we should have a new approach implemented.

**Comment by bahiirwa** [comment]
I have been testing this on local server and online. The plugin unmistakably identifies that woo is installed or files exist on server but which ever way I rewrite the conditional for installing, cc-compat-woo still installs but properly throws the notice.

Screenshot (37)

Screenshot (38)

Of course if it was named `woocommerce\woocommerce.php` there is no way it would install. File error would pop up on installation trial. same folder names and files can not exist on any OS.

**Comment by timbocode** [comment]
Just one quick observation.

Function `display_wc_message()` is still trying to deactivate '`cc-compat-woo/cc-compat-woo.php`'

**Comment by bahiirwa** [comment]
Good catch. However, it doesn’t run. I was trying to merge the gist shared and current files.

**Comment by timbocode** [comment]
OK. I also noticed that you reference '**includes**' in one place and '**inc**' in another:

`include_once dirname( __FILE__ ) . '/includes/UpdateClient.class.php';`
`$link = WP_PLUGIN_DIR . "/cc-compat-woo/inc/functions.php";`

Same reason?

**Comment by bahiirwa** [comment]
I missed the folder from merging #6

**Comment by bahiirwa** [comment]
This logic is no longer needed as the code is in the cc repo

**Pull request closed without merging**
